spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/delivery_system
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
jwt:
  secret: your-256-bit-secret-key-for-jwt-signing
  expiration: 86400000 # 1 day in milliseconds
logging:
  level:
    root: INFO
    org.springframework.jdbc.datasource: DEBUG # Dòng này rất quan trọng
    org.hibernate: DEBUG # Dòng này cũng quan trọng
    com.example.deliverysystem: DEBUG