CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL
);

CREATE TABLE shipper (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    phone_number VARCHAR(255) NOT NULL UNIQUE,
    current_latitude DOUBLE PRECISION,
    current_longitude DOUBLE PRECISION,
    user_id BIGINT UNIQUE,
    CONSTRAINT fk_shipper_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE delivery_trip (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_date DATE NOT NULL,
    status VARCHAR(50),
    shipper_id BIGINT NOT NULL,
    optimized_route_data JSONB,
    CONSTRAINT fk_delivery_trip_shipper FOREIGN KEY (shipper_id) REFERENCES shipper (id)
);

CREATE TABLE package (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_info VARCHAR(255) NOT NULL,
    receiver_info VARCHAR(255) NOT NULL,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    package_details TEXT,
    cod_amount DOUBLE PRECISION,
    status VARCHAR(50),
    notes TEXT,
    proof_of_delivery_url TEXT,
    reconciled BOOLEAN NOT NULL DEFAULT FALSE,
    reconciled_at TIMESTAMPTZ,
    reconciled_by VARCHAR(255),
    delivery_trip_id BIGINT,
    CONSTRAINT fk_package_delivery_trip FOREIGN KEY (delivery_trip_id) REFERENCES delivery_trip (id)
);

CREATE INDEX idx_shipper_user_id ON shipper (user_id);
CREATE INDEX idx_delivery_trip_shipper_id ON delivery_trip (shipper_id);
CREATE INDEX idx_package_delivery_trip_id ON package (delivery_trip_id);
CREATE INDEX idx_package_status ON package (status);
CREATE INDEX idx_package_reconciled ON package (reconciled);
