spring.application.name=delivery-management-system
spring.profiles.default=dev

# Shared OpenAPI configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.packages-to-scan=com.example.deliverysystem.controller
springdoc.paths-to-match=/api/v1/**